services:
  app:
    container_name: coos_task_app
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
    # depends_on:
      # Add dependencies here (refer to lab sheet)
    environment:
      TZ: Asia/Bangkok
      # Add more environment variables here (refer to lab sheet)
  # db: Add the rest of the service here (Also refer to lab sheet)
  # nginx: Add the rest of the service here (Also refer to lab sheet)